### ISSUE TITLE
想过跟 dubbo-js 合并一起发展吗？

### ISSUE THREAD

**Issue by rocky-zh** [cevio/dubbo.ts#2]
我司正在用 dubbo-js，也期望 dubbo-js 社区涌现类似于 dubbo-go 一样的 full stack 框架
https://github.com/apache/dubbo-js/issues/118

**Comment by cevio** [comment]
> 我司正在用 dubbo-js，也期望 dubbo-js 社区涌现类似于 dubbo-go 一样的 full stack 框架
> [apache/dubbo-js#118](https://github.com/apache/dubbo-js/issues/118)

非常感谢您的issue，如果apache愿意接受我的解决方案，我是愿意合并一起发展的。主要是看他们那边的决定。如果不接受的话，我也会一直维护，因为我们公司用的就是dubbo，不可能抛弃掉java的dubbo。
