### ISSUE TITLE
provider发送消息时存在问题

### ISSUE THREAD

**Issue by JeniTurtle** [cevio/dubbo.ts#4]
![image](https://user-images.githubusercontent.com/15798752/76047077-aa9a5780-5f9c-11ea-8d94-29626ca3d9ef.png)

provider context实例执行decode方法时最后触发的事件，执行调用绑定的provider.on('data')事件方法，但是这里处理的事件方法是可能是异步的，就会导致ctx.send()方法在返回结果之前执行。

![image](https://user-images.githubusercontent.com/15798752/76047098-bdad2780-5f9c-11ea-90db-987b1d3bbec7.png)

修改方案：

```typescript
/**
* provider/context.ts
* Context类继承EventEmiter类型
*/
import { EventEmitter } from '@nelts/utils';
export default class Context extends EventEmitter {}
```

```typescript
/**
* provider/context.ts
* decode方法最后面，加上触发结束事件
*/
return this.conn.provider.emit('data', this, chunk, () => {
        this.emit('dataHandlingEnd');
});
```

```typescript
/**
* provider/connection.ts
* 修改onMessage方法
*/
    this._lastread_timestamp = Date.now();
    const ctx = new Context(this, buf);
    ctx.on('dataHandlingEnd', () => {
      if (!ctx.status)
        ctx.status = PROVIDER_CONTEXT_STATUS.OK;
      if (ctx.req)
        this.send(ctx.encode());
    });
    Promise.resolve(ctx.decode()).catch(e => {
        ctx.body = e.message;
        if (!ctx.status || ctx.status === PROVIDER_CONTEXT_STATUS.OK)
            ctx.status = PROVIDER_CONTEXT_STATUS.SERVICE_ERROR;
        ctx.emit('dataHandlingEnd');
    });
```

```typescript
/**
* 调用时，provider.on('data')事件修改
*/
provider.on('data', async (ctx: ProviderContext, chunk: ProviderChunk, next) => {
        // do something...
        next();
} )
```

**Comment by cevio** [comment]
@JeniTurtle 我验证下。

**Comment by cevio** [comment]
> ![image](https://user-images.githubusercontent.com/15798752/76047077-aa9a5780-5f9c-11ea-8d94-29626ca3d9ef.png)
> 
> provider context实例执行decode方法时最后触发的事件，执行调用绑定的provider.on('data')事件方法，但是这里处理的事件方法是可能是异步的，就会导致ctx.send()方法在返回结果之前执行。
> 
> ![image](https://user-images.githubusercontent.com/15798752/76047098-bdad2780-5f9c-11ea-90db-987b1d3bbec7.png)
> 
> 修改方案：
> 
> ```ts
> /**
> * provider/context.ts
> * Context类继承EventEmiter类型
> */
> import { EventEmitter } from '@nelts/utils';
> export default class Context extends EventEmitter {}
> ```
> 
> ```ts
> /**
> * provider/context.ts
> * decode方法最后面，加上触发结束事件
> */
> return this.conn.provider.emit('data', this, chunk, () => {
>         this.emit('dataHandlingEnd');
> });
> ```
> 
> ```ts
> /**
> * provider/connection.ts
> * 修改onMessage方法
> */
>     this._lastread_timestamp = Date.now();
>     const ctx = new Context(this, buf);
>     ctx.on('dataHandlingEnd', () => {
>       if (!ctx.status)
>         ctx.status = PROVIDER_CONTEXT_STATUS.OK;
>       if (ctx.req)
>         this.send(ctx.encode());
>     });
>     Promise.resolve(ctx.decode()).catch(e => {
>         ctx.body = e.message;
>         if (!ctx.status || ctx.status === PROVIDER_CONTEXT_STATUS.OK)
>             ctx.status = PROVIDER_CONTEXT_STATUS.SERVICE_ERROR;
>         ctx.emit('dataHandlingEnd');
>     });
> ```
> 
> ```ts
> /**
> * 调用时，provider.on('data')事件修改
> */
> provider.on('data', async (ctx: ProviderContext, chunk: ProviderChunk, next) => {
>         // do something...
>         next();
> } )
> ```



@JeniTurtle provider.on还是是可以异步的。您没必要这样做的。

```javascript
provider.on('data', async () => {
  // await xxxx();
})
```
不需要再加一个事件。这里的emitter不是nodejs自带的emitter，而且支持异步的emitter. 叫async-emitter。

**Comment by JeniTurtle** [comment]
搜嘎，但是我实际项目运行中，的确出现了这种情况，改完之后就好了

**Comment by JeniTurtle** [comment]
确实没有注意到。不过在项目中运行时，的确出现了不同步的情况，所以才手动处理了一下。等我有时间再尝试重新验证一下，另外再贴上我目前的代码。

```ts
provider.on('data', async (ctx: ProviderContext, chunk: ProviderChunk, next) => {
      try {
        const { method, interfaceName, requestId, interfaceVersion, parameters } = ctx.req;
        // @ts-ignore
        const eggContext: Context = app.createAnonymousContext({
          method: 'RPC',
          url: `/__rpc/dubbo/${interfaceName}/${method}/${interfaceVersion}?requestId=${requestId}`,
        });
        const rpcSerivce = getInstance(eggContext, chunk.interfacetarget);
        const property = rpcSerivce.constructor.prototype[method];
        const middlewares: ComposeMiddleware<Context>[] = dubbo.middlewares || [];
        const bindedMiddlewares: ComposeMiddleware<Context>[] = (
          Reflect.getMetadata(namespace.RPC_MIDDLEWARE, property) || []
        ).slice(0);
        eggContext.rpcContext = ctx;
        bindedMiddlewares.push(async ({ rpcContext }) => {
          const result = await rpcSerivce[method](...parameters);
          rpcContext.body = result;
        });
        const composed = compose<Context>(middlewares.concat(bindedMiddlewares));
        await composed(eggContext).catch(e => app.logger.error(e));
        ctx.status = PROVIDER_CONTEXT_STATUS.OK;
        Container.reset(eggContext[contextId]);
        next();
      } catch (err) {
        app.logger.error(err);
        throw err;
      }
    });
```

**Comment by cevio** [comment]
@JeniTurtle 这个provider其实就是提供数据而已，至于怎么处理还是看用户。目前，我们公司的dubbo部分服务就是nodejs的，至今稳定在线的。
async-emitter就是考虑到异步变同步的情况而编写的。

ps：你上面代码是eggjs的rpc？

**Comment by JeniTurtle** [comment]
dei。话说上一个[问题](https://github.com/cevio/dubbo.ts/issues/3)你那里也没遇到过吗，跑test下面demo的时候，就一直报错。
