### ISSUE TITLE
Error: rpc invoke timeout:NaN

### ISSUE THREAD

**Issue by pomele** [cevio/dubbo.ts#5]
node调用java的provider，provider可正常返回response，但consumer拿不到，0.0.0.0:9001页面提示错误如下：
> Error: rpc invoke timeout:NaN
>     at Invoker.resolveInvokeResult (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:208:36)
>     at Invoker.invoke (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:167:45)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at /Users/lvxianhe1/Documents/work/dubbo.ts/test/client_use_javaProvider.ts:48:20

修改了channel.ts中的send中的timeout的时间为5000，依然是这个错误，请问这是哪里的问题？

还有一个小问题：示例的consumer中有：
`await invoker.invoke('testRpc', [java.combine('com.mifa.stib.common.RpcData', {
    data: {"name":"gxh","age":"18","word":""},
    headers: {
      appName: 'dist',
      platform: 1,
      equipment: 1,
      trace: 'dsafa-dsf-dsaf-sda-f-sa'
    },
    user: {
      id: 1
    },
  }
)])`
我理解java.combine中应该是要转为的java类型，那应该写为类似java.util.Set这样，为什么是com.mifa.stib.common.RpcData，这看起来更像是个interface

**Comment by pomele** [comment]
> node调用java的provider，provider可正常返回response，但consumer拿不到，0.0.0.0:9001页面提示错误如下：
> 
> > Error: rpc invoke timeout:NaN
> > at Invoker.resolveInvokeResult (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:208:36)
> > at Invoker.invoke (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:167:45)
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > at /Users/lvxianhe1/Documents/work/dubbo.ts/test/client_use_javaProvider.ts:48:20
> 
> 修改了channel.ts中的send中的timeout的时间为5000，依然是这个错误，请问这是哪里的问题？
> 
> 还有一个小问题：示例的consumer中有：
> `await invoker.invoke('testRpc', [java.combine('com.mifa.stib.common.RpcData', { data: {"name":"gxh","age":"18","word":""}, headers: { appName: 'dist', platform: 1, equipment: 1, trace: 'dsafa-dsf-dsaf-sda-f-sa' }, user: { id: 1 }, } )])`
> 我理解java.combine中应该是要转为的java类型，那应该写为类似java.util.Set这样，为什么是com.mifa.stib.common.RpcData，这看起来更像是个interface

第一个问题找到了，是因为consumer里的timeout默认写在default.timeout，但是provider是timeout，没有default对象，导致consumer中有些逻辑没有执行，把consumer->channel.ts的第60行this.timeout改为5000（或者其他时间）就可以了

**Comment by cevio** [comment]
> > node调用java的provider，provider可正常返回response，但consumer拿不到，0.0.0.0:9001页面提示错误如下：
> > > Error: rpc invoke timeout:NaN
> > > at Invoker.resolveInvokeResult (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:208:36)
> > > at Invoker.invoke (/Users/lvxianhe1/Documents/work/dubbo.ts/src/consumer/invoker.ts:167:45)
> > > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > > at /Users/lvxianhe1/Documents/work/dubbo.ts/test/client_use_javaProvider.ts:48:20
> > 
> > 
> > 修改了channel.ts中的send中的timeout的时间为5000，依然是这个错误，请问这是哪里的问题？
> > 还有一个小问题：示例的consumer中有：
> > `await invoker.invoke('testRpc', [java.combine('com.mifa.stib.common.RpcData', { data: {"name":"gxh","age":"18","word":""}, headers: { appName: 'dist', platform: 1, equipment: 1, trace: 'dsafa-dsf-dsaf-sda-f-sa' }, user: { id: 1 }, } )])`
> > 我理解java.combine中应该是要转为的java类型，那应该写为类似java.util.Set这样，为什么是com.mifa.stib.common.RpcData，这看起来更像是个interface
> 
> 第一个问题找到了，是因为consumer里的timeout默认写在default.timeout，但是provider是timeout，没有default对象，导致consumer中有些逻辑没有执行，把consumer->channel.ts的第60行this.timeout改为5000（或者其他时间）就可以了

@pomele 这里consumer的timeout来源是provider提供的，所以在注册到zk的时候，provider必须包含timeout值。在dubbo官方文档上，超时时间是由provider控制，而非comsumer控制。具体可以参考这里 [https://github.com/nelts/dubbo/blob/master/src/decorators/timeout.ts](https://github.com/nelts/dubbo/blob/master/src/decorators/timeout.ts) 

我解释下`com.mifa.stib.common.RpcData`这个，其实就是`interface`，而你所看到的只是demo演示时候的名字，具体你调用java的dubbo服务的时候是要根据java约定的interface来填写的。
