### ISSUE TITLE
zookeeper替换成nacos

### ISSUE THREAD

**Issue by noobzhp** [cevio/dubbo.ts#6]
服务注册发现替换成nacos的话能改造吗

**Comment by cevio** [comment]
@noobzhp 正在开发v2版本: https://github.com/cevio/dubbo.ts/tree/v2

可以自定义registry。

**Comment by cevio** [comment]
@noobzhp 你可以通过这个 https://github.com/cevio/dubbo.ts/blob/master/packages/zookeeper/src/index.ts 来模仿nacos的实现。
