### ISSUE TITLE
dubbo.ts 如何调用java的dubbo接口 

### ISSUE THREAD

**Issue by angrycans** [cevio/dubbo.ts#8]
dubbo.ts 如何调用java的dubbo接口 
我试了下 怎么通过zk 总是空的channel
能调用吗 如果可以调用最好给个例子

**Comment by cevio** [comment]
等我修复 https://github.com/cevio/dubbo.ts/commit/6c9fd98551013c8b4065282b54e97e5589fe4c24#diff-ab855dd92bef7941bf4bb6df2b67fd80e007844446efa3a32391c4ce9bb8b912R104

还未测试
